name: "test pull request"
on: [pull_request]

jobs:
  test:
    name: Testing action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Export as default variable GIT_BRANCH_NAME
        uses: ./
        id: getGitBranch1
      - name: Get Git branch name
        run: |-
          echo "GIT_BRANCH_NAME = $GIT_BRANCH_NAME"
          echo "GIT_BRANCH_NAME_HEAD = $GIT_BRANCH_NAME_HEAD"
          echo "GIT_BRANCH_NAME_BASE = $GIT_BRANCH_NAME_BASE"
          echo "Branch name: ${{ steps.getGitBranch1.outputs.git_branch_name }}"
          echo "Branch name: ${{ steps.getGitBranch1.outputs.git_branch_name_head }}"
          echo "Branch name: ${{ steps.getGitBranch1.outputs.git_branch_name_base }}"
      - name: Export with custom variable MY_BRANCH
        uses: ./
        id: getGitBranch2
        with:
          name: MY_BRANCH
      - name: Get custom Git branch name
        run: |-
          echo "MY_BRANCH = $MY_BRANCH"
          echo "MY_BRANCH = $MY_BRANCH_HEAD"
          echo "MY_BRANCH = $MY_BRANCH_BASE"
          echo "Branch name: ${{ steps.getGitBranch2.outputs.git_branch_name }}"
          echo "Branch name: ${{ steps.getGitBranch2.outputs.git_branch_name_head }}"
          echo "Branch name: ${{ steps.getGitBranch2.outputs.git_branch_name_base }}"
